version: "3.9"

services:
  antweb:
    build:
      args:
        ENV: STAGE

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro

  httpd:
    environment:
      ENV: 'STAGE'