version: "3.9"

services:
  mysql:
    ports:
      - "3306"   # Enable when on production server. This will allow internal network access to database
  antweb:
    build:
      context: .
      dockerfile: docker/antweb/Dockerfile
      args:
        ENV: PROD

  httpd:
    environment:
      ENV: 'PROD'