version: "3.9"

services:
  antweb:
    build:
      args:
        ENV: STAGE

  mysql:
    volumes:
      - ./docker/mysql/mysql_stage.cnf:/etc/mysql/conf.d/custom.cnf
  caddy:
    volumes:
      - ./docker/caddy/Caddyfile.staging:/etc/caddy/Caddyfile:ro
