version: "3.9"

services:
  antweb:
    build:
      args:
        ENV: DEV
    ports:
      - "5005:5005"
    environment:
      # >- = YAML block chomp operator -- join lines together with space, remove trailing newline (newline breaks JVM)
      JAVA_OPTS: >-
        -Dlogging.level=debug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Xshare:off

    volumes:
      - ".:/antweb/deploy"
      # These files are normally copied to final folder, since ant deploy doesn't follow symlinks
      # We link them using bind mounts instead so they can be modified without rebuilding the container
      - ./etc/AppResDevDocker.properties:/usr/local/antweb/WEB-INF/classes/AntwebResources.properties
      - ./etc/log4j2.xml:/usr/local/antweb/WEB-INF/classes/log4j2.xml
      - ./WEB-INF/struts-configDbAnt.xml:/usr/local/antweb/WEB-INF/struts-configDb.xml

  api:
    volumes:
      - "./api/v3.1:/api"   # Mount the api dir in the container for making edits without rebuilding
    ports:
    - "127.0.0.1:5000:5000"   #Expose the api outside the container to the local machine for debugging
    command: ["--reload"]


  caddy:
    volumes:
      - ./docker/caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro